<a href="https://colab.research.google.com/github/brettfazio/2017/blob/master/HW_4/Homework4_problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 2
*Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.*



In [0]:
# imports
import numpy as np

In [0]:
def maxpooling2d(input_mat, s):
  if (s > input_mat.shape[0]):
    raise Exception('Invalid maxpooling input, s is larger than the input matrix.')
  
  w_0 = input_mat.shape[0]
  w_1 = input_mat.shape[1]

  new_size_0 = int(w_0 / s)
  new_size_1 = int(w_1 / s)

  output_mat = np.zeros((new_size_0, new_size_1))

  for d in np.arange(new_size_0):
    for a in np.arange(new_size_1):
      # Set up our initial value.
      output_mat[d][a] = input_mat[d*s][a*s]
      for i in np.arange(s):
        for j in np.arange(s):
          output_mat[d][a] = max(output_mat[d][a], input_mat[i+d*s][j+a*s])

  return output_mat

Now I will test the function on a few test cases

This first test case is a valid case that shows off proper padding and returns a valid answer.

In [4]:

my_matrix = np.arange(25).reshape(5,5)

print("Input matrix:")
print(my_matrix)

print("s = 2")

my_result = maxpooling2d(my_matrix, 2)

print("Resulting matrix:")
print(my_result)


Input matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
s = 2
Resulting matrix:
[[ 6.  8.]
 [16. 18.]]


This second case is an invalid case that throws my custom exception.

In [5]:
my_small_matrix = np.arange(16).reshape(4,4)

print("Input matrix:")
print(my_small_matrix)

print("s = 10")

my_result = maxpooling2d(my_small_matrix, 10)

Input matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
s = 10


Exception: ignored

Now I will run it on the provided test cases.

In [7]:
input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])

for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
